version: '3'

services:
  php_apache:
    image: php:7.2-apache  # Utilisez le nom de votre image construite
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - phpmyadmin
    command: sh -c "echo 'phpMyAdmin is ready on http://localhost:8081 and a web page on http://localhost:8080' && apache2-foreground"

  mysql:
    image: mysql
    volumes:
      - ./php/sql/:/docker-entrypoint-initdb.d/initial.sql
      # Le fichier initial.sql sera exécuté lors du démarrage du conteneur
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: utilisateurs
      MYSQL_USER: quentin
      MYSQL_PASSWORD: quentin
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - mysql
